[package]
name = "subproj1"
version = "0.1.0"
authors = ["Kartikaya Gupta <kgupta@mozilla.com>"]

[dependencies]
ipc-channel = { version = "0.5.0", optional = true }

[features]
optional-dep = ["ipc-channel"]
